# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object_location import ObjectLocation  # noqa: F401,E501
from swagger_server import util


class DataReference(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, type: str=None, connection: object=None, location: object=None, schema: object=None):  # noqa: E501
        """DataReference - a model defined in Swagger

        :param name: The name of this DataReference.  # noqa: E501
        :type name: str
        :param type: The type of this DataReference.  # noqa: E501
        :type type: str
        :param connection: The connection of this DataReference.  # noqa: E501
        :type connection: object
        :param location: The location of this DataReference.  # noqa: E501
        :type location: object
        :param schema: The schema of this DataReference.  # noqa: E501
        :type schema: object
        """
        self.swagger_types = {
            'name': str,
            'type': str,
            'connection': object,
            'location': object,
            'schema': object
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'connection': 'connection',
            'location': 'location',
            'schema': 'schema'
        }

        self._name = name
        self._type = type
        self._connection = connection
        self._location = location
        self._schema = schema

    @classmethod
    def from_dict(cls, dikt) -> 'DataReference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The data_reference of this DataReference.  # noqa: E501
        :rtype: DataReference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this DataReference.


        :return: The name of this DataReference.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DataReference.


        :param name: The name of this DataReference.
        :type name: str
        """

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this DataReference.

        The data source type like COS or dashDB. Allowed values for type are 's3' for COS and 'dashdb' for dashDB  # noqa: E501

        :return: The type of this DataReference.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this DataReference.

        The data source type like COS or dashDB. Allowed values for type are 's3' for COS and 'dashdb' for dashDB  # noqa: E501

        :param type: The type of this DataReference.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def connection(self) -> object:
        """Gets the connection of this DataReference.


        :return: The connection of this DataReference.
        :rtype: object
        """
        return self._connection

    @connection.setter
    def connection(self, connection: object):
        """Sets the connection of this DataReference.


        :param connection: The connection of this DataReference.
        :type connection: object
        """
        if connection is None:
            raise ValueError("Invalid value for `connection`, must not be `None`")  # noqa: E501

        self._connection = connection

    @property
    def location(self) -> object:
        """Gets the location of this DataReference.

        For sentiment models, path will be hybrid pipeline id e.g.4cedab6d-e8e4-4214-b81a-2ddb122db2ab. For DL models, path will be training directory name e.g. training-ZZaQeX7mR  # noqa: E501

        :return: The location of this DataReference.
        :rtype: object
        """
        return self._location

    @location.setter
    def location(self, location: object):
        """Sets the location of this DataReference.

        For sentiment models, path will be hybrid pipeline id e.g.4cedab6d-e8e4-4214-b81a-2ddb122db2ab. For DL models, path will be training directory name e.g. training-ZZaQeX7mR  # noqa: E501

        :param location: The location of this DataReference.
        :type location: object
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def schema(self) -> object:
        """Gets the schema of this DataReference.

        https://api.dataplatform.cloud.ibm.com/schemas/common-pipeline/datarecord-metadata/datarecord-metadata-v2-schema.json  # noqa: E501

        :return: The schema of this DataReference.
        :rtype: object
        """
        return self._schema

    @schema.setter
    def schema(self, schema: object):
        """Sets the schema of this DataReference.

        https://api.dataplatform.cloud.ibm.com/schemas/common-pipeline/datarecord-metadata/datarecord-metadata-v2-schema.json  # noqa: E501

        :param schema: The schema of this DataReference.
        :type schema: object
        """

        self._schema = schema
