# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErrorBadRequestTarget(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, name: str=None):  # noqa: E501
        """ErrorBadRequestTarget - a model defined in Swagger

        :param type: The type of this ErrorBadRequestTarget.  # noqa: E501
        :type type: str
        :param name: The name of this ErrorBadRequestTarget.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'type': str,
            'name': str
        }

        self.attribute_map = {
            'type': 'type',
            'name': 'name'
        }

        self._type = type
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorBadRequestTarget':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error_bad_request_target of this ErrorBadRequestTarget.  # noqa: E501
        :rtype: ErrorBadRequestTarget
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ErrorBadRequestTarget.


        :return: The type of this ErrorBadRequestTarget.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ErrorBadRequestTarget.


        :param type: The type of this ErrorBadRequestTarget.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def name(self) -> str:
        """Gets the name of this ErrorBadRequestTarget.


        :return: The name of this ErrorBadRequestTarget.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ErrorBadRequestTarget.


        :param name: The name of this ErrorBadRequestTarget.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
