# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErrorErrors(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, message: str=None, more_info: str=None):  # noqa: E501
        """ErrorErrors - a model defined in Swagger

        :param code: The code of this ErrorErrors.  # noqa: E501
        :type code: str
        :param message: The message of this ErrorErrors.  # noqa: E501
        :type message: str
        :param more_info: The more_info of this ErrorErrors.  # noqa: E501
        :type more_info: str
        """
        self.swagger_types = {
            'code': str,
            'message': str,
            'more_info': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'more_info': 'more_info'
        }

        self._code = code
        self._message = message
        self._more_info = more_info

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorErrors':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error_errors of this ErrorErrors.  # noqa: E501
        :rtype: ErrorErrors
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this ErrorErrors.


        :return: The code of this ErrorErrors.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ErrorErrors.


        :param code: The code of this ErrorErrors.
        :type code: str
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ErrorErrors.


        :return: The message of this ErrorErrors.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorErrors.


        :param message: The message of this ErrorErrors.
        :type message: str
        """

        self._message = message

    @property
    def more_info(self) -> str:
        """Gets the more_info of this ErrorErrors.


        :return: The more_info of this ErrorErrors.
        :rtype: str
        """
        return self._more_info

    @more_info.setter
    def more_info(self, more_info: str):
        """Sets the more_info of this ErrorErrors.


        :param more_info: The more_info of this ErrorErrors.
        :type more_info: str
        """

        self._more_info = more_info
