# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.error_bad_request_target import ErrorBadRequestTarget  # noqa: F401,E501
from swagger_server import util


class ErrorBadRequestErrors(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, message: str=None, target: ErrorBadRequestTarget=None):  # noqa: E501
        """ErrorBadRequestErrors - a model defined in Swagger

        :param code: The code of this ErrorBadRequestErrors.  # noqa: E501
        :type code: str
        :param message: The message of this ErrorBadRequestErrors.  # noqa: E501
        :type message: str
        :param target: The target of this ErrorBadRequestErrors.  # noqa: E501
        :type target: ErrorBadRequestTarget
        """
        self.swagger_types = {
            'code': str,
            'message': str,
            'target': ErrorBadRequestTarget
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'target': 'target'
        }

        self._code = code
        self._message = message
        self._target = target

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorBadRequestErrors':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error_bad_request_errors of this ErrorBadRequestErrors.  # noqa: E501
        :rtype: ErrorBadRequestErrors
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this ErrorBadRequestErrors.


        :return: The code of this ErrorBadRequestErrors.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ErrorBadRequestErrors.


        :param code: The code of this ErrorBadRequestErrors.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ErrorBadRequestErrors.


        :return: The message of this ErrorBadRequestErrors.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorBadRequestErrors.


        :param message: The message of this ErrorBadRequestErrors.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def target(self) -> ErrorBadRequestTarget:
        """Gets the target of this ErrorBadRequestErrors.


        :return: The target of this ErrorBadRequestErrors.
        :rtype: ErrorBadRequestTarget
        """
        return self._target

    @target.setter
    def target(self, target: ErrorBadRequestTarget):
        """Sets the target of this ErrorBadRequestErrors.


        :param target: The target of this ErrorBadRequestErrors.
        :type target: ErrorBadRequestTarget
        """

        self._target = target
