# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.error_bad_request_errors import ErrorBadRequestErrors  # noqa: F401,E501
from swagger_server import util


class ErrorBadRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, trace: str=None, errors: List[ErrorBadRequestErrors]=None):  # noqa: E501
        """ErrorBadRequest - a model defined in Swagger

        :param trace: The trace of this ErrorBadRequest.  # noqa: E501
        :type trace: str
        :param errors: The errors of this ErrorBadRequest.  # noqa: E501
        :type errors: List[ErrorBadRequestErrors]
        """
        self.swagger_types = {
            'trace': str,
            'errors': List[ErrorBadRequestErrors]
        }

        self.attribute_map = {
            'trace': 'trace',
            'errors': 'errors'
        }

        self._trace = trace
        self._errors = errors

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorBadRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error_bad_request of this ErrorBadRequest.  # noqa: E501
        :rtype: ErrorBadRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def trace(self) -> str:
        """Gets the trace of this ErrorBadRequest.


        :return: The trace of this ErrorBadRequest.
        :rtype: str
        """
        return self._trace

    @trace.setter
    def trace(self, trace: str):
        """Sets the trace of this ErrorBadRequest.


        :param trace: The trace of this ErrorBadRequest.
        :type trace: str
        """
        if trace is None:
            raise ValueError("Invalid value for `trace`, must not be `None`")  # noqa: E501

        self._trace = trace

    @property
    def errors(self) -> List[ErrorBadRequestErrors]:
        """Gets the errors of this ErrorBadRequest.


        :return: The errors of this ErrorBadRequest.
        :rtype: List[ErrorBadRequestErrors]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[ErrorBadRequestErrors]):
        """Sets the errors of this ErrorBadRequest.


        :param errors: The errors of this ErrorBadRequest.
        :type errors: List[ErrorBadRequestErrors]
        """
        if errors is None:
            raise ValueError("Invalid value for `errors`, must not be `None`")  # noqa: E501

        self._errors = errors
