# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.metrics_inner import MetricsInner  # noqa: F401,E501
from swagger_server import util


class Metrics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """Metrics - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Metrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The metrics of this Metrics.  # noqa: E501
        :rtype: Metrics
        """
        return util.deserialize_model(dikt, cls)
