# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MetricsInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, timestamp: datetime=None, iteration: float=None, phase: str=None, machine_learning_metrics: object=None):  # noqa: E501
        """MetricsInner - a model defined in Swagger

        :param timestamp: The timestamp of this MetricsInner.  # noqa: E501
        :type timestamp: datetime
        :param iteration: The iteration of this MetricsInner.  # noqa: E501
        :type iteration: float
        :param phase: The phase of this MetricsInner.  # noqa: E501
        :type phase: str
        :param machine_learning_metrics: The machine_learning_metrics of this MetricsInner.  # noqa: E501
        :type machine_learning_metrics: object
        """
        self.swagger_types = {
            'timestamp': datetime,
            'iteration': float,
            'phase': str,
            'machine_learning_metrics': object
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'iteration': 'iteration',
            'phase': 'phase',
            'machine_learning_metrics': 'machine_learning_metrics'
        }

        self._timestamp = timestamp
        self._iteration = iteration
        self._phase = phase
        self._machine_learning_metrics = machine_learning_metrics

    @classmethod
    def from_dict(cls, dikt) -> 'MetricsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The metrics_inner of this MetricsInner.  # noqa: E501
        :rtype: MetricsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this MetricsInner.


        :return: The timestamp of this MetricsInner.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this MetricsInner.


        :param timestamp: The timestamp of this MetricsInner.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def iteration(self) -> float:
        """Gets the iteration of this MetricsInner.


        :return: The iteration of this MetricsInner.
        :rtype: float
        """
        return self._iteration

    @iteration.setter
    def iteration(self, iteration: float):
        """Sets the iteration of this MetricsInner.


        :param iteration: The iteration of this MetricsInner.
        :type iteration: float
        """

        self._iteration = iteration

    @property
    def phase(self) -> str:
        """Gets the phase of this MetricsInner.


        :return: The phase of this MetricsInner.
        :rtype: str
        """
        return self._phase

    @phase.setter
    def phase(self, phase: str):
        """Sets the phase of this MetricsInner.


        :param phase: The phase of this MetricsInner.
        :type phase: str
        """
        allowed_values = ["evaluation", "training"]  # noqa: E501
        if phase not in allowed_values:
            raise ValueError(
                "Invalid value for `phase` ({0}), must be one of {1}"
                .format(phase, allowed_values)
            )

        self._phase = phase

    @property
    def machine_learning_metrics(self) -> object:
        """Gets the machine_learning_metrics of this MetricsInner.


        :return: The machine_learning_metrics of this MetricsInner.
        :rtype: object
        """
        return self._machine_learning_metrics

    @machine_learning_metrics.setter
    def machine_learning_metrics(self, machine_learning_metrics: object):
        """Sets the machine_learning_metrics of this MetricsInner.


        :param machine_learning_metrics: The machine_learning_metrics of this MetricsInner.
        :type machine_learning_metrics: object
        """

        self._machine_learning_metrics = machine_learning_metrics
