# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.node_parameters_object_inner import NodeParametersObjectInner  # noqa: F401,E501
from swagger_server import util


class NodeParametersObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """NodeParametersObject - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NodeParametersObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The node_parameters_object of this NodeParametersObject.  # noqa: E501
        :rtype: NodeParametersObject
        """
        return util.deserialize_model(dikt, cls)
