# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NodeParametersObjectInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, node_id: str=None, parameters: object=None):  # noqa: E501
        """NodeParametersObjectInner - a model defined in Swagger

        :param node_id: The node_id of this NodeParametersObjectInner.  # noqa: E501
        :type node_id: str
        :param parameters: The parameters of this NodeParametersObjectInner.  # noqa: E501
        :type parameters: object
        """
        self.swagger_types = {
            'node_id': str,
            'parameters': object
        }

        self.attribute_map = {
            'node_id': 'node_id',
            'parameters': 'parameters'
        }

        self._node_id = node_id
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'NodeParametersObjectInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The node_parameters_object_inner of this NodeParametersObjectInner.  # noqa: E501
        :rtype: NodeParametersObjectInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node_id(self) -> str:
        """Gets the node_id of this NodeParametersObjectInner.


        :return: The node_id of this NodeParametersObjectInner.
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id: str):
        """Sets the node_id of this NodeParametersObjectInner.


        :param node_id: The node_id of this NodeParametersObjectInner.
        :type node_id: str
        """

        self._node_id = node_id

    @property
    def parameters(self) -> object:
        """Gets the parameters of this NodeParametersObjectInner.


        :return: The parameters of this NodeParametersObjectInner.
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: object):
        """Sets the parameters of this NodeParametersObjectInner.


        :param parameters: The parameters of this NodeParametersObjectInner.
        :type parameters: object
        """

        self._parameters = parameters
