# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PipelineObjectDataBindings(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data_reference_name: str=None, node_id: str=None):  # noqa: E501
        """PipelineObjectDataBindings - a model defined in Swagger

        :param data_reference_name: The data_reference_name of this PipelineObjectDataBindings.  # noqa: E501
        :type data_reference_name: str
        :param node_id: The node_id of this PipelineObjectDataBindings.  # noqa: E501
        :type node_id: str
        """
        self.swagger_types = {
            'data_reference_name': str,
            'node_id': str
        }

        self.attribute_map = {
            'data_reference_name': 'data_reference_name',
            'node_id': 'node_id'
        }

        self._data_reference_name = data_reference_name
        self._node_id = node_id

    @classmethod
    def from_dict(cls, dikt) -> 'PipelineObjectDataBindings':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The pipeline_object_data_bindings of this PipelineObjectDataBindings.  # noqa: E501
        :rtype: PipelineObjectDataBindings
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_reference_name(self) -> str:
        """Gets the data_reference_name of this PipelineObjectDataBindings.

        the input_data_reference name that is the input for the node identified by node_id  # noqa: E501

        :return: The data_reference_name of this PipelineObjectDataBindings.
        :rtype: str
        """
        return self._data_reference_name

    @data_reference_name.setter
    def data_reference_name(self, data_reference_name: str):
        """Sets the data_reference_name of this PipelineObjectDataBindings.

        the input_data_reference name that is the input for the node identified by node_id  # noqa: E501

        :param data_reference_name: The data_reference_name of this PipelineObjectDataBindings.
        :type data_reference_name: str
        """

        self._data_reference_name = data_reference_name

    @property
    def node_id(self) -> str:
        """Gets the node_id of this PipelineObjectDataBindings.

        the id of the pipeline node that will receive the associated input_data_reference input  # noqa: E501

        :return: The node_id of this PipelineObjectDataBindings.
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id: str):
        """Sets the node_id of this PipelineObjectDataBindings.

        the id of the pipeline node that will receive the associated input_data_reference input  # noqa: E501

        :param node_id: The node_id of this PipelineObjectDataBindings.
        :type node_id: str
        """

        self._node_id = node_id
