# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StatusMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, level: str=None, text: str=None):  # noqa: E501
        """StatusMessage - a model defined in Swagger

        :param level: The level of this StatusMessage.  # noqa: E501
        :type level: str
        :param text: The text of this StatusMessage.  # noqa: E501
        :type text: str
        """
        self.swagger_types = {
            'level': str,
            'text': str
        }

        self.attribute_map = {
            'level': 'level',
            'text': 'text'
        }

        self._level = level
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'StatusMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The status_message of this StatusMessage.  # noqa: E501
        :rtype: StatusMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def level(self) -> str:
        """Gets the level of this StatusMessage.


        :return: The level of this StatusMessage.
        :rtype: str
        """
        return self._level

    @level.setter
    def level(self, level: str):
        """Sets the level of this StatusMessage.


        :param level: The level of this StatusMessage.
        :type level: str
        """

        self._level = level

    @property
    def text(self) -> str:
        """Gets the text of this StatusMessage.


        :return: The text of this StatusMessage.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this StatusMessage.


        :param text: The text of this StatusMessage.
        :type text: str
        """

        self._text = text
