# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TagsInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: str=None, description: str=None):  # noqa: E501
        """TagsInner - a model defined in Swagger

        :param value: The value of this TagsInner.  # noqa: E501
        :type value: str
        :param description: The description of this TagsInner.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'value': str,
            'description': str
        }

        self.attribute_map = {
            'value': 'value',
            'description': 'description'
        }

        self._value = value
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'TagsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tags_inner of this TagsInner.  # noqa: E501
        :rtype: TagsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> str:
        """Gets the value of this TagsInner.


        :return: The value of this TagsInner.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this TagsInner.


        :param value: The value of this TagsInner.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def description(self) -> str:
        """Gets the description of this TagsInner.


        :return: The description of this TagsInner.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TagsInner.


        :param description: The description of this TagsInner.
        :type description: str
        """

        self._description = description
