# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_reference import DataReference  # noqa: F401,E501
from swagger_server.models.experiment_object import ExperimentObject  # noqa: F401,E501
from swagger_server.models.object_location import ObjectLocation  # noqa: F401,E501
from swagger_server.models.pipeline_object import PipelineObject  # noqa: F401,E501
from swagger_server.models.tags import Tags  # noqa: F401,E501
from swagger_server import util


class TrainingResourceEntityRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, tags: Tags=None, experiment: ExperimentObject=None, pipeline: PipelineObject=None, training_data_references: List[DataReference]=None, results_reference: ObjectLocation=None):  # noqa: E501
        """TrainingResourceEntityRequest - a model defined in Swagger

        :param tags: The tags of this TrainingResourceEntityRequest.  # noqa: E501
        :type tags: Tags
        :param experiment: The experiment of this TrainingResourceEntityRequest.  # noqa: E501
        :type experiment: ExperimentObject
        :param pipeline: The pipeline of this TrainingResourceEntityRequest.  # noqa: E501
        :type pipeline: PipelineObject
        :param training_data_references: The training_data_references of this TrainingResourceEntityRequest.  # noqa: E501
        :type training_data_references: List[DataReference]
        :param results_reference: The results_reference of this TrainingResourceEntityRequest.  # noqa: E501
        :type results_reference: ObjectLocation
        """
        self.swagger_types = {
            'tags': Tags,
            'experiment': ExperimentObject,
            'pipeline': PipelineObject,
            'training_data_references': List[DataReference],
            'results_reference': ObjectLocation
        }

        self.attribute_map = {
            'tags': 'tags',
            'experiment': 'experiment',
            'pipeline': 'pipeline',
            'training_data_references': 'training_data_references',
            'results_reference': 'results_reference'
        }

        self._tags = tags
        self._experiment = experiment
        self._pipeline = pipeline
        self._training_data_references = training_data_references
        self._results_reference = results_reference

    @classmethod
    def from_dict(cls, dikt) -> 'TrainingResourceEntityRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The training_resource_entity_request of this TrainingResourceEntityRequest.  # noqa: E501
        :rtype: TrainingResourceEntityRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tags(self) -> Tags:
        """Gets the tags of this TrainingResourceEntityRequest.


        :return: The tags of this TrainingResourceEntityRequest.
        :rtype: Tags
        """
        return self._tags

    @tags.setter
    def tags(self, tags: Tags):
        """Sets the tags of this TrainingResourceEntityRequest.


        :param tags: The tags of this TrainingResourceEntityRequest.
        :type tags: Tags
        """

        self._tags = tags

    @property
    def experiment(self) -> ExperimentObject:
        """Gets the experiment of this TrainingResourceEntityRequest.


        :return: The experiment of this TrainingResourceEntityRequest.
        :rtype: ExperimentObject
        """
        return self._experiment

    @experiment.setter
    def experiment(self, experiment: ExperimentObject):
        """Sets the experiment of this TrainingResourceEntityRequest.


        :param experiment: The experiment of this TrainingResourceEntityRequest.
        :type experiment: ExperimentObject
        """

        self._experiment = experiment

    @property
    def pipeline(self) -> PipelineObject:
        """Gets the pipeline of this TrainingResourceEntityRequest.


        :return: The pipeline of this TrainingResourceEntityRequest.
        :rtype: PipelineObject
        """
        return self._pipeline

    @pipeline.setter
    def pipeline(self, pipeline: PipelineObject):
        """Sets the pipeline of this TrainingResourceEntityRequest.


        :param pipeline: The pipeline of this TrainingResourceEntityRequest.
        :type pipeline: PipelineObject
        """

        self._pipeline = pipeline

    @property
    def training_data_references(self) -> List[DataReference]:
        """Gets the training_data_references of this TrainingResourceEntityRequest.


        :return: The training_data_references of this TrainingResourceEntityRequest.
        :rtype: List[DataReference]
        """
        return self._training_data_references

    @training_data_references.setter
    def training_data_references(self, training_data_references: List[DataReference]):
        """Sets the training_data_references of this TrainingResourceEntityRequest.


        :param training_data_references: The training_data_references of this TrainingResourceEntityRequest.
        :type training_data_references: List[DataReference]
        """
        if training_data_references is None:
            raise ValueError("Invalid value for `training_data_references`, must not be `None`")  # noqa: E501

        self._training_data_references = training_data_references

    @property
    def results_reference(self) -> ObjectLocation:
        """Gets the results_reference of this TrainingResourceEntityRequest.


        :return: The results_reference of this TrainingResourceEntityRequest.
        :rtype: ObjectLocation
        """
        return self._results_reference

    @results_reference.setter
    def results_reference(self, results_reference: ObjectLocation):
        """Sets the results_reference of this TrainingResourceEntityRequest.


        :param results_reference: The results_reference of this TrainingResourceEntityRequest.
        :type results_reference: ObjectLocation
        """
        if results_reference is None:
            raise ValueError("Invalid value for `results_reference`, must not be `None`")  # noqa: E501

        self._results_reference = results_reference
